# Generated by Django 5.0.6 on 2024-06-29 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0002_rename_usuario_usuarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usuarios',
            new_name='usuario',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='repositorio_usuarios',
        ),
    ]
